# -*- coding: utf-8 -*-
"""
Package tai_nguyen
==================
Chứa các thành phần tài nguyên, tiền tệ và điểm cống hiến trong Chu Thiên Vạn Giới:
1. linh_thach: Đơn vị tiền tệ cơ bản (Hạ - Trung - Thượng - Cực phẩm).
2. tien_thach: Tiền tệ cao cấp dành cho tu sĩ từ Vấn Đỉnh hoặc Nhị Bộ Cảnh trở lên.
3. diem_cong_hien: Đơn vị công đức Tông Môn đổi công pháp, đan dược, pháp bảo và đặc quyền.
"""
from .linh_thach import (
    LINH_THACH_DATA,
    LINH_THACH_BY_ID,
    LINH_THACH_BY_KEY,
    LINH_THACH_BY_TIER,
    LINH_THACH_BY_CODE,
    RATE_HA_TO_TRUNG,
    RATE_TRUNG_TO_THUONG,
    RATE_THUONG_TO_CUC,
    VALUE_HA_PHAM,
    VALUE_TRUNG_PHAM,
    VALUE_THUONG_PHAM,
    VALUE_CUC_PHAM,
    get_all_linh_thach,
    get_linh_thach_by_id,
    get_linh_thach_by_key,
    get_linh_thach_by_tier,
    quy_doi_sang_ha_pham,
    quy_doi_tu_ha_pham,
    dinh_dang_linh_thach,
)

from .tien_thach import (
    TIEN_THACH_DATA,
    TIEN_THACH_BY_ID,
    TIEN_THACH_BY_KEY,
    TIEN_THACH_BY_TIER,
    TIEN_THACH_BY_CODE,
    TIEN_THACH_TO_LINH_THACH_RATE,
    RATE_CUC_LINH_TO_HA_TIEN,
    RATE_HA_TO_TRUNG_TIEN,
    RATE_TRUNG_TO_THUONG_TIEN,
    RATE_THUONG_TO_CUC_TIEN,
    VALUE_HA_PHAM_TIEN,
    VALUE_TRUNG_PHAM_TIEN,
    VALUE_THUONG_PHAM_TIEN,
    VALUE_CUC_PHAM_TIEN,
    MIN_REALM_ID_FOR_TIEN_THACH,
    MIN_REALM_NAME_FOR_TIEN_THACH,
    get_all_tien_thach,
    get_tien_thach_by_id,
    get_tien_thach_by_key,
    get_tien_thach_by_tier,
    kiem_tra_tu_vi_su_dung_tien_thach,
    quy_doi_tien_thach_sang_linh_thach,
    quy_doi_tu_ha_pham_tien,
    dinh_dang_tien_thach,
)

from .diem_cong_hien import (
    NGUON_TICH_LUY,
    DANH_MUC_DOI_THUONG,
    TOTAL_MUC_DOI,
    MUC_DOI_BY_ID,
    MUC_DOI_BY_KEY,
    get_all_muc_doi,
    get_muc_doi_by_id,
    get_muc_doi_by_key,
    get_muc_doi_by_category,
    kiem_tra_du_diem_doi,
)

__all__ = [
    # linh_thach
    "LINH_THACH_DATA",
    "LINH_THACH_BY_ID",
    "LINH_THACH_BY_KEY",
    "LINH_THACH_BY_TIER",
    "LINH_THACH_BY_CODE",
    "RATE_HA_TO_TRUNG",
    "RATE_TRUNG_TO_THUONG",
    "RATE_THUONG_TO_CUC",
    "VALUE_HA_PHAM",
    "VALUE_TRUNG_PHAM",
    "VALUE_THUONG_PHAM",
    "VALUE_CUC_PHAM",
    "get_all_linh_thach",
    "get_linh_thach_by_id",
    "get_linh_thach_by_key",
    "get_linh_thach_by_tier",
    "quy_doi_sang_ha_pham",
    "quy_doi_tu_ha_pham",
    "dinh_dang_linh_thach",
    # tien_thach
    "TIEN_THACH_DATA",
    "TIEN_THACH_BY_ID",
    "TIEN_THACH_BY_KEY",
    "TIEN_THACH_BY_TIER",
    "TIEN_THACH_BY_CODE",
    "TIEN_THACH_TO_LINH_THACH_RATE",
    "RATE_CUC_LINH_TO_HA_TIEN",
    "RATE_HA_TO_TRUNG_TIEN",
    "RATE_TRUNG_TO_THUONG_TIEN",
    "RATE_THUONG_TO_CUC_TIEN",
    "VALUE_HA_PHAM_TIEN",
    "VALUE_TRUNG_PHAM_TIEN",
    "VALUE_THUONG_PHAM_TIEN",
    "VALUE_CUC_PHAM_TIEN",
    "MIN_REALM_ID_FOR_TIEN_THACH",
    "MIN_REALM_NAME_FOR_TIEN_THACH",
    "get_all_tien_thach",
    "get_tien_thach_by_id",
    "get_tien_thach_by_key",
    "get_tien_thach_by_tier",
    "kiem_tra_tu_vi_su_dung_tien_thach",
    "quy_doi_tien_thach_sang_linh_thach",
    "quy_doi_tu_ha_pham_tien",
    "dinh_dang_tien_thach",
    # diem_cong_hien
    "NGUON_TICH_LUY",
    "DANH_MUC_DOI_THUONG",
    "TOTAL_MUC_DOI",
    "MUC_DOI_BY_ID",
    "MUC_DOI_BY_KEY",
    "get_all_muc_doi",
    "get_muc_doi_by_id",
    "get_muc_doi_by_key",
    "get_muc_doi_by_category",
    "kiem_tra_du_diem_doi",
]
