# -*- coding: utf-8 -*-
"""
Package canh_gioi_chung
=======================
Cung cấp toàn bộ hệ thống cảnh giới dùng chung cho bot tu tiên:
1. Cảnh giới tu vi (canh_gioi_tu_vi)
2. Cảnh giới pháp bảo (canh_gioi_phap_bao)
3. Cảnh giới phù triện (canh_gioi_phu_trien)
4. Cảnh giới đan dược (canh_gioi_dan_duoc)
"""

# Cảnh giới tu vi (Mặc định cho các hàm không tiền tố để tương thích)
from .canh_gioi_tu_vi import (
    REALMS,
    TOTAL_REALMS,
    REALM_BLUEPRINT,
    REALM_BY_ID,
    REALM_BY_NAME,
    get_all_realms,
    get_realm_by_id,
    get_realm_by_name,
    get_next_realm,
    is_max_realm,
    # Alias rõ nghĩa
    REALMS as TU_VI_REALMS,
    TOTAL_REALMS as TOTAL_TU_VI_REALMS,
    get_all_realms as get_all_tu_vi_realms,
    get_realm_by_id as get_tu_vi_realm_by_id,
    get_realm_by_name as get_tu_vi_realm_by_name,
    get_next_realm as get_next_tu_vi_realm,
    is_max_realm as is_max_tu_vi_realm,
)

# Cảnh giới pháp bảo (thay thế binh khí)
from .canh_gioi_phap_bao import (
    REALMS as PHAP_BAO_REALMS,
    TREASURE_REALMS,
    TOTAL_REALMS as TOTAL_PHAP_BAO_REALMS,
    TOTAL_TREASURE_REALMS,
    get_all_realms as get_all_phap_bao_realms,
    get_realm_by_id as get_phap_bao_realm_by_id,
    get_realm_by_name as get_phap_bao_realm_by_name,
    get_next_realm as get_next_phap_bao_realm,
    is_max_realm as is_max_phap_bao_realm,
    get_all_treasure_realms,
    get_treasure_realm_by_id,
    get_treasure_realm_by_name,
    get_next_treasure_realm,
    is_max_treasure_realm,
    # Tương thích ngược với tên gọi binh khí
    BINH_KHI_REALMS,
    WEAPON_REALMS,
    TOTAL_BINH_KHI_REALMS,
    TOTAL_WEAPON_REALMS,
    get_all_binh_khi_realms,
    get_binh_khi_realm_by_id,
    get_binh_khi_realm_by_name,
    get_next_binh_khi_realm,
    is_max_binh_khi_realm,
    get_all_weapon_realms,
    get_weapon_realm_by_id,
    get_weapon_realm_by_name,
    get_next_weapon_realm,
    is_max_weapon_realm,
)

# Cảnh giới phù triện (thay thế công pháp)
from .canh_gioi_phu_trien import (
    REALMS as PHU_TRIEN_REALMS,
    TALISMAN_REALMS,
    TOTAL_REALMS as TOTAL_PHU_TRIEN_REALMS,
    TOTAL_TALISMAN_REALMS,
    get_all_realms as get_all_phu_trien_realms,
    get_realm_by_id as get_phu_trien_realm_by_id,
    get_realm_by_name as get_phu_trien_realm_by_name,
    get_next_realm as get_next_phu_trien_realm,
    is_max_realm as is_max_phu_trien_realm,
    get_all_talisman_realms,
    get_talisman_realm_by_id,
    get_talisman_realm_by_name,
    get_next_talisman_realm,
    is_max_talisman_realm,
    # Tương thích ngược với tên gọi công pháp
    CONG_PHAP_REALMS,
    SKILL_REALMS,
    TOTAL_CONG_PHAP_REALMS,
    TOTAL_SKILL_REALMS,
    get_all_cong_phap_realms,
    get_cong_phap_realm_by_id,
    get_cong_phap_realm_by_name,
    get_next_cong_phap_realm,
    is_max_cong_phap_realm,
    get_all_skill_realms,
    get_skill_realm_by_id,
    get_skill_realm_by_name,
    get_next_skill_realm,
    is_max_skill_realm,
)

# Cảnh giới đan dược (thay thế di tích)
from .canh_gioi_dan_duoc import (
    REALMS as DAN_DUOC_REALMS,
    PILL_REALMS,
    ELIXIR_REALMS,
    TOTAL_REALMS as TOTAL_DAN_DUOC_REALMS,
    TOTAL_DAN_DUOC_REALMS as TOTAL_PILL_REALMS,
    get_all_realms as get_all_dan_duoc_realms,
    get_realm_by_id as get_dan_duoc_realm_by_id,
    get_realm_by_name as get_dan_duoc_realm_by_name,
    get_next_realm as get_next_dan_duoc_realm,
    is_max_realm as is_max_dan_duoc_realm,
    get_all_pill_realms,
    get_pill_realm_by_id,
    get_pill_realm_by_name,
    get_next_pill_realm,
    is_max_pill_realm,
    # Tương thích ngược với tên gọi di tích
    DI_TICH_REALMS,
    RELIC_REALMS,
    RUINS_REALMS,
    TOTAL_DI_TICH_REALMS,
    TOTAL_RELIC_REALMS,
    get_all_di_tich_realms,
    get_di_tich_realm_by_id,
    get_di_tich_realm_by_name,
    get_next_di_tich_realm,
    is_max_di_tich_realm,
    get_all_relic_realms,
    get_relic_realm_by_id,
    get_relic_realm_by_name,
    get_next_relic_realm,
    is_max_relic_realm,
)

__all__ = [
    # Tu vi
    "REALMS",
    "TOTAL_REALMS",
    "REALM_BLUEPRINT",
    "REALM_BY_ID",
    "REALM_BY_NAME",
    "get_all_realms",
    "get_realm_by_id",
    "get_realm_by_name",
    "get_next_realm",
    "is_max_realm",
    "TU_VI_REALMS",
    "TOTAL_TU_VI_REALMS",
    "get_all_tu_vi_realms",
    "get_tu_vi_realm_by_id",
    "get_tu_vi_realm_by_name",
    "get_next_tu_vi_realm",
    "is_max_tu_vi_realm",
    # Pháp bảo
    "PHAP_BAO_REALMS",
    "TREASURE_REALMS",
    "TOTAL_PHAP_BAO_REALMS",
    "TOTAL_TREASURE_REALMS",
    "get_all_phap_bao_realms",
    "get_phap_bao_realm_by_id",
    "get_phap_bao_realm_by_name",
    "get_next_phap_bao_realm",
    "is_max_phap_bao_realm",
    "get_all_treasure_realms",
    "get_treasure_realm_by_id",
    "get_treasure_realm_by_name",
    "get_next_treasure_realm",
    "is_max_treasure_realm",
    # Binh khí (tương thích ngược)
    "BINH_KHI_REALMS",
    "WEAPON_REALMS",
    "TOTAL_BINH_KHI_REALMS",
    "TOTAL_WEAPON_REALMS",
    "get_all_binh_khi_realms",
    "get_binh_khi_realm_by_id",
    "get_binh_khi_realm_by_name",
    "get_next_binh_khi_realm",
    "is_max_binh_khi_realm",
    "get_all_weapon_realms",
    "get_weapon_realm_by_id",
    "get_weapon_realm_by_name",
    "get_next_weapon_realm",
    "is_max_weapon_realm",
    # Phù triện
    "PHU_TRIEN_REALMS",
    "TALISMAN_REALMS",
    "TOTAL_PHU_TRIEN_REALMS",
    "TOTAL_TALISMAN_REALMS",
    "get_all_phu_trien_realms",
    "get_phu_trien_realm_by_id",
    "get_phu_trien_realm_by_name",
    "get_next_phu_trien_realm",
    "is_max_phu_trien_realm",
    "get_all_talisman_realms",
    "get_talisman_realm_by_id",
    "get_talisman_realm_by_name",
    "get_next_talisman_realm",
    "is_max_talisman_realm",
    # Công pháp (tương thích ngược)
    "CONG_PHAP_REALMS",
    "SKILL_REALMS",
    "TOTAL_CONG_PHAP_REALMS",
    "TOTAL_SKILL_REALMS",
    "get_all_cong_phap_realms",
    "get_cong_phap_realm_by_id",
    "get_cong_phap_realm_by_name",
    "get_next_cong_phap_realm",
    "is_max_cong_phap_realm",
    "get_all_skill_realms",
    "get_skill_realm_by_id",
    "get_skill_realm_by_name",
    "get_next_skill_realm",
    "is_max_skill_realm",
    # Đan dược
    "DAN_DUOC_REALMS",
    "PILL_REALMS",
    "ELIXIR_REALMS",
    "TOTAL_DAN_DUOC_REALMS",
    "TOTAL_PILL_REALMS",
    "get_all_dan_duoc_realms",
    "get_dan_duoc_realm_by_id",
    "get_dan_duoc_realm_by_name",
    "get_next_dan_duoc_realm",
    "is_max_dan_duoc_realm",
    "get_all_pill_realms",
    "get_pill_realm_by_id",
    "get_pill_realm_by_name",
    "get_next_pill_realm",
    "is_max_pill_realm",
    # Di tích (tương thích ngược)
    "DI_TICH_REALMS",
    "RELIC_REALMS",
    "RUINS_REALMS",
    "TOTAL_DI_TICH_REALMS",
    "TOTAL_RELIC_REALMS",
    "get_all_di_tich_realms",
    "get_di_tich_realm_by_id",
    "get_di_tich_realm_by_name",
    "get_next_di_tich_realm",
    "is_max_di_tich_realm",
    "get_all_relic_realms",
    "get_relic_realm_by_id",
    "get_relic_realm_by_name",
    "get_next_relic_realm",
    "is_max_relic_realm",
]
